fail job when anything fails in previous matrix

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -227,11 +227,18 @@ jobs:
           flags: integration
 
   integration-report:
+    if: ${{ always() }}
     name: Integration Test Suite
     runs-on: ubuntu-latest
     needs: integration
     steps:
-      - name: "[Notification] Integration test suite passes"
+      - name: "Integration Tests Failed"
+        if: ${{ contains(needs.integration.result, 'failure') || contains(needs.integration.result, 'cancelled') }}
+        run: |
+          echo "::notice title="Integration test suite failed""
+          exit 1
+
+      - name: "Integration Tests Passes"
         run: |
           echo "::notice title="Integration test suite passes""
 
