revert testing workflow
2

diff --git a/.github/workflows/test-repeater.yml b/.github/workflows/test-repeater.yml
--- a/.github/workflows/test-repeater.yml
+++ b/.github/workflows/test-repeater.yml
@@ -1,109 +1,164 @@
 # **what?**
-# Generates and commits pytest-split test duration data for optimized test splitting.
+# This workflow will test all test(s) at the input path given number of times to determine if it's flaky or not.  You can test with any supported OS/Python combination.
+# This is batched in 10 to allow more test iterations faster.
 
 # **why?**
-# pytest-split uses duration data to balance test workloads across workers.
-# Without this data, tests are split evenly by count which can cause imbalanced runs.
+# Testing if a test is flaky and if a previously flaky test has been fixed.  This allows easy testing on supported python versions and OS combinations.
 
 # **when?**
-# Runs weekly on Sunday at midnight UTC, and can be manually triggered as needed.
+# This is triggered manually from dbt-core.
 
-name: Update Test Durations
+name: Flaky Tester
 
 on:
-  schedule:
-    - cron: "0 0 * * 0"
   workflow_dispatch:
+    inputs:
+      branch:
+        description: "Branch to check out"
+        type: string
+        required: true
+        default: "main"
+      test_path:
+        description: "Path to single test to run (ex: tests/functional/retry/test_retry.py::TestRetry::test_fail_fast)"
+        type: string
+        required: true
+        default: "tests/functional/..."
+      python_version:
+        description: "Version of Python to Test Against"
+        type: choice
+        options:
+          - "3.10"
+          - "3.11"
+      os:
+        description: "OS to run test in"
+        type: choice
+        options:
+          - "ubuntu-latest"
+          - "macos-14"
+          - "windows-latest"
+      num_runs_per_batch:
+        description: "Max number of times to run the test per batch.  We always run 10 batches."
+        type: number
+        required: true
+        default: "50"
 
-permissions:
-  contents: write
+permissions: read-all
 
 defaults:
   run:
     shell: bash
 
 jobs:
-  generate-durations:
-    name: "Generate Test Durations"
+  debug:
+    runs-on: ${{ vars.UBUNTU_LATEST }}
+    steps:
+      - name: "[DEBUG] Output Inputs"
+        run: |
+          echo "Branch: ${{ inputs.branch }}"
+          echo "test_path: ${{ inputs.test_path }}"
+          echo "python_version: ${{ inputs.python_version }}"
+          echo "os: ${{ inputs.os }}"
+          echo "num_runs_per_batch: ${{ inputs.num_runs_per_batch }}"
 
-    runs-on: ubuntu-latest
-    timeout-minutes: 360
-
+  pytest:
+    runs-on: ${{ inputs.os }}
+    strategy:
+      # run all batches, even if one fails.  This informs how flaky the test may be.
+      fail-fast: false
+      # using a matrix to speed up the jobs since the matrix will run in parallel when runners are available
+      matrix:
+        batch: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"]
     env:
-      DBT_INVOCATION_ENV: github-actions
+      PYTEST_ADDOPTS: "-v --color=yes -n4 --csv integration_results.csv"
       DBT_TEST_USER_1: dbt_test_user_1
       DBT_TEST_USER_2: dbt_test_user_2
       DBT_TEST_USER_3: dbt_test_user_3
-
-    services:
-      postgres:
-        image: postgres
-        env:
-          POSTGRES_PASSWORD: password
-          POSTGRES_USER: postgres
-        options: >-
-          --health-cmd pg_isready
-          --health-interval 10s
-          --health-timeout 5s
-          --health-retries 5
-        ports:
-          - 5432:5432
+      DD_CIVISIBILITY_AGENTLESS_ENABLED: true
+      DD_API_KEY: ${{ secrets.DATADOG_API_KEY }}
+      DD_SITE: datadoghq.com
+      DD_ENV: ci
+      DD_SERVICE: ${{ github.event.repository.name }}
 
     steps:
-      - name: "Check out the repository"
+      - name: "Checkout code"
         uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # actions/checkout@v4
+        with:
+          ref: ${{ inputs.branch }}
 
-      - name: "Set up Python 3.11"
+      - name: "Setup Python"
         uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # actions/setup-python@v6
         with:
-          python-version: "3.11"
-
-      - name: "Run postgres setup script"
-        run: ./scripts/setup_db.sh
-        env:
-          PGHOST: localhost
-          PGPORT: 5432
-          PGPASSWORD: password
+          python-version: "${{ inputs.python_version }}"
 
       - name: "Install hatch"
         uses: pypa/hatch@257e27e51a6a5616ed08a39a408a21c35c9931bc # pypa/hatch@install
 
-      - name: "Run integration tests and store durations"
+      - name: "Setup Dev Environment"
         run: |
           cd core
-          hatch -v run ci:integration-tests -- --store-durations --durations-path .test_durations || true
+          hatch run setup
 
-      - name: "Code quality"
+      - name: "Set up postgres (linux)"
+        if: inputs.os == '${{ vars.UBUNTU_LATEST }}'
         run: |
           cd core
-          git add .test_durations
-          hatch run pre-commit run end-of-file-fixer --files .test_durations || true
+          hatch run setup-db
 
-      - name: "Commit updated durations file"
-        run: |
-          git config user.name "Github Build Bot"
-          git config user.email "buildbot@fishtownanalytics.com"
-          if [ -f core/.test_durations ]; then
-            git add core/.test_durations
-            git diff --staged --quiet || git commit -m "Update test durations for pytest-split"
-            git push
-          else
-            echo "No .test_durations file generated"
-            exit 1
-          fi
-
-  slack-notification:
-    runs-on: ubuntu-latest
-    needs: [generate-durations]
-    steps:
-      - name: "Post Slack Notification"
-        uses: ravsamhq/notify-slack-action@be814b201e233b2dc673608aa46e5447c8ab13f2 # ravsamhq/notify-slack-action@v2
+        # mac and windows don't use make due to limitations with docker with those runners in GitHub
+      - name: Set up postgres (macos)
+        if: runner.os == 'macOS'
+        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # nick-fields/retry@v3
         with:
-          status: ${{ job.status}}
-          token: ${{ secrets.GITHUB_TOKEN }}
-          notification_title: "Update Test Durations Failed"
-          message_format: "{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}@{branch}> on <{commit_url}|{commit_sha}>"
-          footer: "<{run_url}|View Run>"
-          notify_when: "failure"
-        env:
-          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_DEV_CORE_ALERTS }}
+          timeout_minutes: 10
+          max_attempts: 3
+          command: ./scripts/setup_db.sh
+
+      - name: "Set up postgres (windows)"
+        if: inputs.os == 'windows-latest'
+        uses: ./.github/actions/setup-postgres-windows
+
+      - name: "Test Command"
+        id: command
+        run: |
+          test_command="python -m pytest ${{ inputs.test_path }}"
+          echo "test_command=$test_command" >> $GITHUB_OUTPUT
+
+      - name: "Run test ${{ inputs.num_runs_per_batch }} times"
+        id: pytest
+        run: |
+          set +e
+          for ((i=1; i<=${{ inputs.num_runs_per_batch }}; i++))
+          do
+            echo "Running pytest iteration $i..."
+            python -m pytest --ddtrace ${{ inputs.test_path }}
+            exit_code=$?
+
+            if [[ $exit_code -eq 0 ]]; then
+              success=$((success + 1))
+              echo "Iteration $i: Success"
+            else
+              failure=$((failure + 1))
+              echo "Iteration $i: Failure"
+            fi
+
+            echo
+            echo "==========================="
+            echo "Successful runs: $success"
+            echo "Failed runs: $failure"
+            echo "==========================="
+            echo
+          done
+
+          echo "failure=$failure" >> $GITHUB_OUTPUT
+
+      - name: "Success and Failure Summary: ${{ inputs.os }}/Python ${{ inputs.python_version }}"
+        run: |
+          echo "Batch: ${{ matrix.batch }}"
+          echo "Successful runs: ${{ steps.pytest.outputs.success }}"
+          echo "Failed runs: ${{ steps.pytest.outputs.failure }}"
+
+      - name: "Error for Failures"
+        if: ${{ steps.pytest.outputs.failure }}
+        run: |
+          echo "Batch ${{ matrix.batch }} failed ${{ steps.pytest.outputs.failure }} of ${{ inputs.num_runs_per_batch }} tests"
+          exit 1
